spring:
  application:
    name: simply_schedule_backend_monolithic

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

    jpa:
      hibernate:
        ddl-auto: update # Options: none, validate, update, create, create-drop
      show-sql: true     # Show SQL queries in the console
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.H2Dialect # Adjust to your database

  h2:
    console:
      enabled: true
      path: /h2-console # Path to access the H2 console

server:
  port: 8080