spring:
  application:
    name: simply_schedule_backend_monolithic

  datasource:
    url: jdbc:h2:./data/testdb;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop # Options: none, validate, update, create, create-drop
    show-sql: true     # Show SQL queries in the console
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect # Adjust to your database

  h2:
    console:
      enabled: true
      path: /h2-console # Path to access the H2 console

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
#  sql:
#    init:
#      mode: never

server:
  port: 8080

google_client_id:
  client: 692439382840-504o7a0lrmdf94htqgh2fivar19rj13d.apps.googleusercontent.com
  admin: 692439382840-idf8gu35b4qsn481gfg0esel9tgmqa3v.apps.googleusercontent.com